### ISSUE TITLE
ELAN system to be added

### ISSUE THREAD

**Issue by cormacanderson** [cldf/clts#131]
https://tla.mpi.nl/tools/tla-tools/elan/ipa-extension/

**Comment by xrotwang** [comment]
@cormacanderson do you know, how these extensions are used within ELAN? You'd want to add the right column symbols to BIPA, right? The left hand side seem to be key bindings to produce the glyphs in the right column.
Alternatively, this table could just be provided as an Orthography Profile?

**Comment by cormacanderson** [comment]
Hey Robert. Yes, I put up the issue after discussing with @LinguList, but now you have me rethinking. Really this is effectively an entry system like SAMPA, rather than a fully-fledged transcription system like the Uralic Phonetic Alphabet, or BIPA. The symbols on the right hand side should already be in the BIPA, I imagine. Better perhaps then to just close this issue?

**Comment by xrotwang** [comment]
I think it might be useful as orthography profile, so maybe we should move the issue to https://github.com/cldf/orthograpy

**Comment by tresoldi** [comment]
Look as a profile for me too. Luckily, one that should be very easy to do.

**Comment by cormacanderson** [comment]
Okay, cool. Will open an issue there then and put it in, then link and close this one. Does that work?

**Comment by cormacanderson** [comment]
Opened https://github.com/cldf/orthograpy/issues/1 replacing this issue, so closing here
