### ISSUE TITLE
Trigraphs cannot be linked with tie-bars

### ISSUE THREAD

**Issue by OwenAmarasi** [cldf/clts#132]
In our data we have prenasalised affricates such as:

ɲ͡d͡ʒ and ɲ͡t͡ʃ

but when we use two tie bars only the first two symbols are joined e.g. <ɲ͡d͡ʒ> = `ɲd ʒ`

**Comment by LinguList** [comment]
This is not a problem of CLTS, but of your IPA. You should write a superscript nasal `n` (indicates pre-nasalization). Tie bars are generally ignored in CLTS, as we do not need them, since we segment the data actively, with spaces.

**Comment by OwenAmarasi** [comment]
OK, thanks.

Gereon is looking into how to handle this.

All the best,
Owen
