### ISSUE TITLE
Add support for voiced palatal lateral fricative consonant

### ISSUE THREAD

**Issue by Anaphory** [cldf/clts#134]
Our Nga'o data contains, according to the analyst, (optionally pre-stopped) voiced palatal lateral fricative consonants, for which [Wikipedia](https://en.wikipedia.org/wiki/Voiced_palatal_lateral_fricative) suggests ʎ̝ (157 429) as transcription. This is supported in neither direction by BIPA:

```
>>> import pyclts
>>> bipa = pyclts.TranscriptionSystem("bipa")
>>> bipa["ʎ̝"]
UnknownSound(ts=<pyclts.transcriptionsystem.TranscriptionSystem object at 0x7fc2baa267f0>, grapheme='ʎ̝', source='ʎ̝', generated=False, note=None)
>>> bipa["ʎ̝"[0]]
<pyclts.models.Consonant: voiced palatal lateral approximant consonant>
>>> bipa["voiced palatal lateral fricative consonant"]
<pyclts.models.Consonant: voiced palatal lateral fricative consonant>
>>> str(bipa["voiced palatal lateral fricative consonant"])
'<?><!>'
```

Can I convince you that this sound should be part of BIPA? What would I have to do to make BIPA support it?

**Comment by LinguList** [comment]
Easiest way to add this sound is: open `src/transcriptionsystems/bipa/consonants.tsv` and add the sound actively, along with its definition features. The practice is straightforward:

Grapheme comes to the first column of the row. 

Phonation, place, manner are required, so you put `voiced palatal fricative` there. You ignore the alias column, and add the remeaining features in extra: laterality:lateral.

That's it. Make sure all columns are filled out (so don't leave a tsv file with unequal column length. 

Then run the tests to make sure you don't break averythin before makinga  PR. If you break something, check the fails and get back to us if you're lost.

**Comment by xrotwang** [comment]
Data repository moved to https://github.com/cldf-clts/clts
