### ISSUE TITLE
UnicodeMixin has been deprecated

### ISSUE THREAD

**Issue by Anaphory** [cldf/clts#135]
The UnicodeMixin class used in 

https://github.com/cldf/clts/blob/80ff1a55d025541d6e5f6c6cea37e2c26fa82510/src/pyclts/models.py#L52

has been [deprecated](https://github.com/clld/clldutils/blob/945a7a2179221c24c5f2e776e73a308bc22d6901/src/clldutils/misc.py#L132) and should not be used any more.

**Comment by xrotwang** [comment]
Yes, we'll fix this when dropping py2 support.

**Comment by Anaphory** [comment]
Ah, okay. I had (too) many warnings sweep by in my travis build of LexiRumah, so I created this and then made a hack to my travis config to ignore those deprecation warnings. (Can [the warnings bit](https://github.com/clld/clldutils/blob/945a7a2179221c24c5f2e776e73a308bc22d6901/src/clldutils/misc.py#L132) be made to output the warning only once?)

**Comment by Anaphory** [comment]
Is there a way this problem can be solved by putting the right requirements in `setup.py`? Obviously for py>3.5, it does not have to pin to `clldutils<3.0.0`, but for earlier python it does – can that logic be expressed and would it be useful?

**Comment by xrotwang** [comment]
Yes, it can. See the setup.py in pyglottolog

Gereon Kaiping <notifications@github.com> schrieb am Mi., 18. Sep. 2019,
15:49:

**Comment by xrotwang** [comment]
See https://github.com/cldf-clts/pyclts
