### ISSUE TITLE
Adding sounds to CLTS

### ISSUE THREAD

**Issue by thiagochacon** [cldf/clts#25]
Attaching sounds to CALC (http://calc.digling.org/clts/) would be an interesting addition. Some websites would already provide a way to link to the IPA, such as

http://web.uvic.ca/ling/resources/ipa/charts/IPAlab/IPAlab.htm

or wikipedia

**Comment by LinguList** [comment]
I just added a couple of sounds, but more are here (vowels missing, etc): 
* http://web.uvic.ca/ling/resources/ipa/charts/IPAlab/IPAsounds/
