### ISSUE TITLE
web presentation: clld or light-weight custom JS

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#38]
The current web-presentation is a very simple [JS-only app](http://calc.digling.org/clts/). It will be easy to further expand the web-app to e.g., allow for translation across alphabets and other things. The advantage is that I can push this myself, while I'd need more guidance and help with a clld application. It also seems that right now we do not serve that much data there, but rather a software-tool, so client-based seems enough to handle the data. On the other hand, having a clld-app would of course add the look-and-feel for users that might make it easier to be used. I am open to either solution, but as minimal requirements, I think we should try to have:

- [ ] a lookup system similar to the one we already have, with links to the TranscriptionData, but which additionally allows users to pick one of the available transcription systems before entering data (this will be trivial to implement, I think)
- [ ] a translation system that allows users to insert data in one transcription system and then tries to translate it
- [ ] some information and references for each transcription system and transcription dataset we use.

**Comment by xrotwang** [comment]
I think a custom JS app is very appropriate in this case, because the app can also serve as example of how to integrate CLTS into in-house workflows.

**Comment by LinguList** [comment]
Yes, good point. In some sense, it's not more than a simple JS plugin.
