### ISSUE TITLE
Custom CLTS Web Presentation

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#39]
- [x] a lookup system similar to the one we already have, with links to the TranscriptionData, but which additionally allows users to pick one of the available transcription systems before entering data (this will be trivial to implement, I think)
- [ ] a translation system that allows users to insert data in one transcription system and then tries to translate it
- [ ] some information and references for each transcription system and transcription dataset we use.
- [ ] try to mimick the CLDF-website look-and-feel (the HTML/CSS skeleton) so that users know it's the same brand

This is based on the decision taken in #38.

**Comment by LinguList** [comment]
Update: we now also have a webreference that provides basic information of the data both as simple table and in json. Format is simple: just write down the name, and this provides all information we currently have on it:

* http://lingulist.de/clts/clts.py?name=voiceless%20bilabial%20stop%20consonant

Yields:

![screenshot_2018-01-04_15-38-54](https://user-images.githubusercontent.com/2916210/34568214-6674176e-f165-11e7-8ca7-674dc61cd234.png)

and if you write http://lingulist.de/clts/clts.py?name=voiceless%20bilabial%20stop%20consonant?plain=true

you'll get JSON.

**Comment by LinguList** [comment]
This is a simple python-cgi script and a sqlite-database which runs it, but it is probably convenient to serve as the background information provider if we want to reference sounds via some kind of ontology.

**Comment by tresoldi** [comment]
Nice! I can already think of many ways to use and extend this, including a
Wikipédia botar.

Em 4 de jan de 2018 12:40 PM, "Johann-Mattis List" <notifications@github.com>
escreveu:

This is a simple python-cgi script and a sqlite-database which runs it, but
it is probably convenient to serve as the background information provider
if we want to reference sounds via some kind of ontology.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cldf/clts/issues/39#issuecomment-355298545>, or mute
the thread

**Comment by LinguList** [comment]
The same works with plain javascript:

* http://lingulist.de/clts/?voiced bilabial stop consonant

But it's a bit of an overkill, as it needs to load the sql.js library and also the sqlite database. So better stick to simple Python.

**Comment by tresoldi** [comment]
Great logo for CLTS, too.

**Comment by LinguList** [comment]
The web-interface for simple query has further been changed, and added to the basic query. In principle, we could even leave it there: The translation functions etc. are already covered by the python code, and people can query all sounds that are there in the data now. This means, we can use a simple landing page, a query page, and that's it. Even a simple landing page with query on the same page may suffice, we'll just link to github (similar to the cldf website) for tutorials and the like.

**Comment by LinguList** [comment]
Okay, we have the raw strucutre of the clld app now, and will take over from there.
