### ISSUE TITLE
switch to frozensets as representation of feature bundles and no longer modify a TS on the fly?

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#55]
The problem (but also a feature that we want) of BIPA is that generated sounds will be remembered and can be retrieved and compared through the system. 

The reason why we have this behavior originally is that it seemed that we could properly display stages of character distortion (wrong order, etc.) and aliases along with their base sounds. It seems however, that this may not even be needed, and we could as well NOT add the generated sounds to the TS-object but just re-create them multiple times when doing an analysis (and later decide to add them officially). 

Right now, we have a problem of order: if we generate and add sounds in one order and then add them in another order, the results will differ, which hints of course to a distortion and something difficult to handle.

It seems better to NOT add any sound to the data, ideally under now circumstances.

**Comment by xrotwang** [comment]
Yes, I ran into this, too. Maybe the lists of sounds should be frozensets?

**Comment by LinguList** [comment]
In order to prevent that they can be changed? I was just testing (will PR later, if I added more sounds from lexibank, we're close to 800 for the real test set now), whether we can't get rid of TS._add and all those modifying things altogether. It seems, the processes are a bit too complex to be handled completely in such a way that we can say that all sounds will always be parsed the same way if we change the underlying database, but I also think this is fine, as we may also change features in the future, which would anyway change the parsing, but in this way, we could have a predictable handling for generated sounds in one release each. For now, most of the features I want to have (re-ordering of badly ordered sounds, like khw -> kwh, predictable handling of what counts as "normalized", "alias", and "generated") are more or less there. Getting rid of ```_add``` would also slim the code down, at the single cost of having to computationally parse those sounds which are not in a database, but here I imagine that we pick generated sounds between releases and add them to our BIPA, which will then serve as the major reference of what is possible and accepted (also in terms of aliases), so it could grow a bit "broader" with time, accepting some older traditions, but only where they are clearly recognizable as an alias.

**Comment by LinguList** [comment]
Yes, addon: we have the same behavior, if we just discard the ```_add```, and the ```_update_regex``` functions, also the same low amount of only two errors in the sounds in phoible, and we have a predictable output for the sounds [here](https://github.com/cldf/clts/blob/master/tests/data/test_data.tsv), with a small amount of unknown sounds.

**Comment by LinguList** [comment]
sorry, was not really getting this until in the morning: I was thinking about handling feature bundles like "voiced labial stop consonant" as frozenset, but we'd need an extra class for this, as for diphthongs and clusters, the order is crucial to detect the from- and the -to element. For now, we can handle bad order of feature descriptions, as in: ```bipa['labial voiced stop consonant'] == bipa['voiced labial stop consonant']```, and the former sound will be labeled as "generated" (which is probably not the best idea, but could be captured in the code). For now, as the features are unordered when calling a ```Sound()```, we can capture the cases, but parsing would be ambiguous for diphthongs and clusters (as we may have identical features in the two components). So a frozenset implementation would have to have the following strategy when constructing the sound:

* check for cluster information, take linearity into account, split the two components, and compare the two components against our frozensets
* if no cluster/diphthong is encountered, directly check for frozenset, if not, construct the sound by calling the ```Sound()``` function.

Maybe the better solution after all, as we'd get rid of the stupid code that orders things and labels them as "generated", etc. For the construction of the grapheme-representation, we'd have to stick to the above-mentioned procedure, but we should no longer add new sounds to the TS on the fly.

**Comment by LinguList** [comment]
Works faster with frozensets, and much more consistent in the expected behavior.
