### ISSUE TITLE
Re-organizing the __main__.py file: moving website creation and transcription data creation

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#57]
For the moment, the ```__main__``` contains code to prepare the metadata as well as the website. I'd say that we better move this code somewhere else, maybe to ```clts/prepare-data.py``` or similar, as this code is nothing we want users to run regularly via commandline, since it changes content in the package. 

It is needless to say that we need an automated routine to create both website and links to phoible, etc., but as we may as well manually correct the links to phoible, and the sound classes, we may better put this into an extra script that can be run, but should not be that easy to run as currently.

The question is: where? At the package level, as I said before, right next to the `setup.py`? Or better somewhere else? And how should be best call it?

**Comment by xrotwang** [comment]
I'll take care of that. Have a couple more changes for the tests in the making, so please don't merge anything big :)

**Comment by LinguList** [comment]
okay, excellent, but note that I have a bigger merge with revised tests, especially on the tone-system, which doesn not work with frozensets (i.e., I worked on the #55 issue and consider it solved, but did not yet do the PR, [compare](https://github.com/lingulist/clts). Should I PR now, so you can see what I chagned?

**Comment by LinguList** [comment]
I started doing this by moving code to the cookbook.
