### ISSUE TITLE
[New TranscriptionData] Database of Eurasian Phonological Inventories

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#59]
* http://eurasianphonology.info/segments

Interesting, they offer their download as json, and they plot all their segments in feature charts. Nice.

**Comment by LinguList** [comment]
Even better: they show syllable structures, their [json](http://eurasianphonology.info/static/phono_dbase.json) dump is quite rich.

**Comment by LinguList** [comment]
And they have source code that [parses IPA](https://github.com/macleginn/eurasian-phonologies/blob/master/src/IPAParser.py)1

**Comment by LinguList** [comment]
So this means, we can use their data to check against ours, and we can even use their code to derive their feature sets (also good for comparison).

**Comment by tresoldi** [comment]
Very, very nice, indeed! Just a pity they don't cite the actual sources,
only that

> [t]he data were gleaned from grammatical descriptions of individual
language varieties and reference works on language families. No recycling
of existing databases was undertaken."

2017-12-17 18:55 GMT-02:00 Johann-Mattis List <notifications@github.com>:

**Comment by tresoldi** [comment]
Oh, the sources are actually there in individual language inventory listing! Really good!

**Comment by tresoldi** [comment]
Found the paper: https://www.academia.edu/35110101/The_Database_of_Eurasian_Phonological_Inventories_a_research_tool_for_distributional_phonological_typology

**Comment by LinguList** [comment]
Yes, spotted this right away when I inspected their JSON. The Python code looks very convenient to use, and it is comforting to see that despite of their nice code and feature system, it is still clear that a system like CLTS is more flexible to rule the big bulk of inconsistencies and communicate between different systems, so we can clearly profit from linking to this dataset and adding features we still don't cover (like pre-labialization), without stepping on each others shoes.

**Comment by LinguList** [comment]
Yes, that's how I found the database, I should've posted it here as well, the paper.
