### ISSUE TITLE
dental sibilant affricate consonant should be re-spelled 

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#63]
We don't need to have the ugly dentality marker under both sounds, it is enough if its under the sibilant fricative.

**Comment by cormacanderson** [comment]
In other words, the same solution here as with prenasalised sounds, an underspecified first element, e.g. ⁿb for conventional ᵐb, and ts̪ for t̪s̪.

**Comment by LinguList** [comment]
Yes, we define underspecification rules. I think this is reasonable, and increases visability. We should write down the principles of graphemes we pick:

* visability/readability
* writability (write three rather than four symbols, etc.)
* simplicity (prefer the simpler system)
* feasability (there are not too many superscript nasals for alls sounds, e.g., if you have superscript n-dental, you would have NO possibility to write it, so it would be inconsistent, which is also why I am against homorganic nasals if they serve only to express pre-nasalization)
