### ISSUE TITLE
Do we have pre-aspirattion and pre-labialization?

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#73]
We find it in the North-Eurasian database, but I am not sure whether this is something that is really needed. If it is needed, we'll need to refine the features which are now subsumed under "preceding". But we could also just ignore it in the first version.

**Comment by tresoldi** [comment]
Pre-aspiration is basically a preceding [h], I think it could be mapped as cluster of h+consonant (line in Ladefoged & Maddieson (1996), e.g. /hk/ instead of /ʰk/).

Not sure about pre-labialization, isn't it a prosodic property?

**Comment by LinguList** [comment]
I mean, pre-aspiration is handled already, but we have but one feature with four +x values:

feature: preceding, values: pre-aspirated or pre-labialized (if we wanted to add it) or pre-glottalized, etc.

So the problem is to name the feature, if we have both, as this will require to have two features, since we can't have two feature values at the same time. But I never heard anything about pre-labialization, so I wonder whether we should add yet another feature or be satisfied for the moment. The current inventory we have (see [here](http://calc.digling.org/clts/), just updated it today, also interesting to see differences between the systtems) already has some 3000 sounds (still need to count how many are aliases, but I suppose: less than one might think...)

**Comment by tresoldi** [comment]
On the consistency, I fully agree and the current solution seems good enough: once more, if researchers in the future plan to extend this, everything is in place.

As for pre-labialization, I found some references on Raimy & Cairns (2015), *The Segment in Phonetics and Phonology* (large portions of the text are available on Google Books, at least from Brazil), but they are not explicit enough. I **think** it refers to the secondary articulation extending from the coda to the nucleus: the vowel would be somewhat labialized (rounded) when the following consonant has this feature (it is similar to what is described as the spiratization of vowels in some Sino-Tibetan languages, when the frication of a consonant extends to a following vowel -- the current headache for my system).

Of course it is a matter of analysis, one could say that labialization will naturally start a little earlier or that the feature actually develops a kind of diphtong. In any case, as Raimy & Cairns claim (p. 85), it is not contrastive in any known language and I don't think it should be included, at least for the time being. If one really needs it, make an alias with "normal" labialization.

**Comment by tresoldi** [comment]
BTW, one of the examples in the same reference seem to imply that it applies not only to preceding vowels, but also consonants: with complex codas, if C1 is not labialized and C2 is labialized, the labialization movement would begin before the realization of C1 is finished. No need to mention that this seems perfectly natural and hardly contrastive.

**Comment by LinguList** [comment]
good, excellent, this means, we may consider accounting for this in some future or in some parallel universe, but we don't bother now, as we don't bother with the whistling sounds.
