### ISSUE TITLE
Decide about release timeline

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#93]
We should realistically decide about a good release date for CLTS. We can do this when we meet with @xrotwang next time (should be next week, if I'm not mistaken).

**Comment by tresoldi** [comment]
I need to finish the transcription systems I offered to implement. I'll try
to do it over the weekend.

2018-01-18 14:58 GMT-02:00 Johann-Mattis List <notifications@github.com>:

**Comment by LinguList** [comment]
We're fine with the time, and we can add new things later, but the more when submitting the paper first, the better, of course. I'll give full attention to the draft from next week (after an important public presentation on Saturday). In terms of release time, I think, a first beta-release 0.1 or similar is feasible for April, maybe even March. We'll decide with @xrotwang and let you all know via this thread.

**Comment by xrotwang** [comment]
Yes, will be in Jena next Monday. Was distracted by a tree falling on my house today :)
