### ISSUE TITLE
Tones on vowels are not properly handled

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#96]
Our fundamental check is the reverse generation of sounds, but this does not work with vowels + tones:

```python
In [3]: bipa['ê']
Out[3]: <pyclts.models.Vowel: unrounded close-mid front with_falling_tone vowel>

In [4]: bipa['ê'].s
Out[4]: 'ê'

In [5]: bipa['unrounded close-mid front with_falling_tone vowel'].s
Out[5]: '<?>̂'
```

Our requirement is that the ".s" attribute is identical with the ".name" attribute when generating sounds from the name or from the grapheme.

**Comment by LinguList** [comment]
Here's the solution: In models.py, add tonal features to the EXCLUDE FEATURES:

```
EXCLUDE_FEATURES = ['apical', 'laminal', 'ejective', 
        'with_falling_tone',
        'with_extra_low_tone',
        'with_extra-high_tone',
        'with_falling_tone',
        'with_low_tone',
        'with_global_fall',
        'with_global_rise',
        'with_high_tone',
        'with_mid_tone',
        'with_rising_tone',
        'with_upstep'
        ]
```

**Comment by tresoldi** [comment]
Do you want me to include it in the PR I am preparing?

**Comment by LinguList** [comment]
Yes, please. Maybe also correct the "with_extra-high_tone" into "with_extra_high_tone"
