### ISSUE TITLE
Mid-long and ultra-short consonants: do we need them?

### ISSUE THREAD

**Issue by LinguList** [cldf/clts#97]
When testing on the [phonetic alignment benchmark](http://alignments.lingpy.org) I found many ultra-short consonants as well as mid-long consonants. I guess this is dialect data which is often very fine-grained. The question is, whether we want to add these to the diacritics, or leave them at the side for the time being.

**Comment by LinguList** [comment]
I don't like having 13 issues, so I'll close this now, and we can re-open whenever we think it should be needed.

**Comment by tresoldi** [comment]
I've opened one for the Wikipedia data, but I should be able to close it by
tonight.

2018-01-31 10:42 GMT-02:00 Johann-Mattis List <notifications@github.com>:

**Comment by LinguList** [comment]
I'll just shut this for the moment, in general, we more or less already decided that we don't bother now, right?
